// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monopoly.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Monopoly.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MonopolyDbContext))]
    [Migration("20260903193908_XpAwarded")]
    partial class XpAwarded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monopoly.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Columns")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.BoardSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BoardVersionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("HouseCost")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("MortgageValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PropertyGroupId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<decimal[]>("RentOverrides")
                        .HasColumnType("numeric[]");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardVersionId");

                    b.ToTable("BoardSpaces");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.BoardVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardVersions");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaisseCommuneDeckOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChanceDeckOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CountsForXpAndClassements")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("DoublesInARow")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FreeParkingPot")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<int>("LastDie1")
                        .HasColumnType("integer");

                    b.Property<int>("LastDie2")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<decimal>("PendingDebtAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PendingDebtCreditorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PendingPurchaseSpaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerParticipantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("XpAwarded")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.GameEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Sequence");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.GameParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("BotDifficulty")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("GetOutOfJailCards")
                        .HasColumnType("integer");

                    b.Property<string>("GuestSecret")
                        .HasColumnType("text");

                    b.Property<bool>("InPrison")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBankrupt")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<int>("JailTurnsElapsed")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<decimal>("Money")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("SeatOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TokenColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GuestSecret");

                    b.ToTable("GameParticipants");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakSubject")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.PropertyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("PropertyGroups");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.PropertyOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardSpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasHotel")
                        .HasColumnType("boolean");

                    b.Property<int>("Houses")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMortgaged")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "BoardSpaceId")
                        .IsUnique();

                    b.ToTable("PropertyOwnerships");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.TradeOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OfferedMoney")
                        .HasColumnType("numeric");

                    b.Property<string>("OfferedSpaceIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProposerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RequestedMoney")
                        .HasColumnType("numeric");

                    b.Property<string>("RequestedSpaceIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Status");

                    b.ToTable("TradeOffers");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.BoardSpace", b =>
                {
                    b.HasOne("Monopoly.Domain.Entities.BoardVersion", null)
                        .WithMany("Spaces")
                        .HasForeignKey("BoardVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.BoardVersion", b =>
                {
                    b.HasOne("Monopoly.Domain.Entities.Board", null)
                        .WithMany("Versions")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.Game", b =>
                {
                    b.OwnsOne("Monopoly.Domain.Entities.GameOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("ArgentDepart")
                                .HasColumnType("numeric");

                            b1.Property<bool>("CagnotteVacances")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ConstructionEquilibree")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Encheres")
                                .HasColumnType("boolean");

                            b1.Property<bool>("HypothequeSansLoyer")
                                .HasColumnType("boolean");

                            b1.Property<bool>("LoyerDoubleEnsembleComplet")
                                .HasColumnType("boolean");

                            b1.Property<bool>("MelangerOrdreJoueurs")
                                .HasColumnType("boolean");

                            b1.Property<bool>("PasDeLoyerEnPrison")
                                .HasColumnType("boolean");

                            b1.Property<int>("TurnLimit")
                                .HasColumnType("integer");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Options")
                        .IsRequired();
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.GameEvent", b =>
                {
                    b.HasOne("Monopoly.Domain.Entities.Game", null)
                        .WithMany("Events")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.GameParticipant", b =>
                {
                    b.HasOne("Monopoly.Domain.Entities.Game", null)
                        .WithMany("Participants")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.PropertyGroup", b =>
                {
                    b.HasOne("Monopoly.Domain.Entities.Board", null)
                        .WithMany("PropertyGroups")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.Board", b =>
                {
                    b.Navigation("PropertyGroups");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.BoardVersion", b =>
                {
                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("Monopoly.Domain.Entities.Game", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
